/*
 * Pipeline Telluric Effect Modeller
 */
package ru.gss.ptemodeller.calculation;

import javax.swing.text.DefaultFormatterFactory;
import org.jdesktop.application.Action;
import ru.gss.ptemodeller.commons.DlgDirEdit;
import ru.gss.ptemodeller.commons.NoLocaleNumberFormatter;
import ru.gss.ptemodeller.data.Reper;

/**
 * Dialog for edit of reper.
 * @version 1.1.0 03.04.2020
 * @author Sergey Guskov
 */
public class DlgReperEdit extends DlgDirEdit < Reper > {

    /**
     * Constructor.
     */
    public DlgReperEdit() {
        super();
        initComponents();
        jftfCoord1.setFormatterFactory(new DefaultFormatterFactory(new NoLocaleNumberFormatter(2)));
        jftfCoord2.setFormatterFactory(new DefaultFormatterFactory(new NoLocaleNumberFormatter(2)));
    }

    /**
     * Setter editing object.
     * @param aTempObj editing object
     */
    @Override
    public void setTempObj(final Reper aTempObj) {
        putTempObj(aTempObj);
        jcbType.setSelectedIndex(getTempObj().getType());
        jftfCoord1.setValue(getTempObj().getCoord1() * 1e-3);
        jftfCoord2.setValue(getTempObj().getCoord2() * 1e-3);
        jtfName.setText(getTempObj().getName());
        getRootPane().setDefaultButton(jbtnOk);
    }

    /**
     * Init new object.
     * @return new object
     */
    @Override
    public Reper createTempObj() {
        return new Reper();
    }

    /**
     * Action for Cancel button.
     */
    @Action
    public void acCancel() {
        setChangeObj(false);
    }

    /**
     * Action for OK button.
     */
    @Action
    public void acOk() {
        if (checkFormattedTextFieldNullNoSupposed(jftfCoord1, -1e4, 1e4)) {
            return;
        }
        if (checkFormattedTextFieldNullNoSupposed(jftfCoord2, -1e4, 1e4)) {
            return;
        }
        if (checkTextField(jtfName)) {
            return;
        }
        getTempObj().setType(jcbType.getSelectedIndex());
        getTempObj().setCoord1(getDoubleFromFormattedTextField(jftfCoord1) * 1e3);
        getTempObj().setCoord2(getDoubleFromFormattedTextField(jftfCoord2) * 1e3);
        getTempObj().setName(jtfName.getText());
        setChangeObj(true);
    }

    //CHECKSTYLE:OFF
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnOk = new javax.swing.JButton();
        jbtnCancel = new javax.swing.JButton();
        jftfCoord1 = new javax.swing.JFormattedTextField();
        jftfCoord2 = new javax.swing.JFormattedTextField();
        jcbType = new javax.swing.JComboBox();
        jtfName = new javax.swing.JTextField();
        jlbType = new javax.swing.JLabel();
        jlbCoord1 = new javax.swing.JLabel();
        jlbCoord2 = new javax.swing.JLabel();
        jlbText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(ru.gss.ptemodeller.PTEModellerApp.class).getContext().getResourceMap(DlgReperEdit.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setModal(true);
        setName("Form"); // NOI18N
        setResizable(false);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(ru.gss.ptemodeller.PTEModellerApp.class).getContext().getActionMap(DlgReperEdit.class, this);
        jbtnOk.setAction(actionMap.get("acOk")); // NOI18N
        jbtnOk.setName("jbtnOk"); // NOI18N

        jbtnCancel.setAction(actionMap.get("acCancel")); // NOI18N
        jbtnCancel.setName("jbtnCancel"); // NOI18N

        jftfCoord1.setName("jftfCoord1"); // NOI18N

        jftfCoord2.setName("jftfCoord2"); // NOI18N

        jcbType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Точка", "Интервал" }));
        jcbType.setName("jcbType"); // NOI18N

        jtfName.setText(resourceMap.getString("jtfName.text")); // NOI18N
        jtfName.setName("jtfName"); // NOI18N

        jlbType.setText(resourceMap.getString("jlbType.text")); // NOI18N
        jlbType.setName("jlbType"); // NOI18N

        jlbCoord1.setText(resourceMap.getString("jlbCoord1.text")); // NOI18N
        jlbCoord1.setName("jlbCoord1"); // NOI18N

        jlbCoord2.setText(resourceMap.getString("jlbCoord2.text")); // NOI18N
        jlbCoord2.setName("jlbCoord2"); // NOI18N

        jlbText.setText(resourceMap.getString("jlbText.text")); // NOI18N
        jlbText.setName("jlbText"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbtnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbCoord2)
                            .addComponent(jlbCoord1)
                            .addComponent(jlbType))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcbType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jftfCoord2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jftfCoord1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)))
                    .addComponent(jlbText)
                    .addComponent(jtfName, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbType)
                    .addComponent(jcbType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jftfCoord1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbCoord1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jftfCoord2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbCoord2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnOk)
                    .addComponent(jbtnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnCancel;
    private javax.swing.JButton jbtnOk;
    private javax.swing.JComboBox jcbType;
    private javax.swing.JFormattedTextField jftfCoord1;
    private javax.swing.JFormattedTextField jftfCoord2;
    private javax.swing.JLabel jlbCoord1;
    private javax.swing.JLabel jlbCoord2;
    private javax.swing.JLabel jlbText;
    private javax.swing.JLabel jlbType;
    private javax.swing.JTextField jtfName;
    // End of variables declaration//GEN-END:variables
    //CHECKSTYLE:ON
}
